name: Saludo con variables
on: workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: hola
    steps:
      - name: Saludo variables
        run: echo "$SALUDO, ${{secrets.SALUDO_SECRETO}}" 